import React from "react";
import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useStore } from "../store/store";

import Code from "../components/Code";

const GameScore = dynamic(() => import("../components/GameScore"), {
  ssr: false,
});

const Home: NextPage = () => {
  const latestGame = useStore((state) => state.latestGame);
  const setLatestGame = useStore((state) => state.setLatestGame);

  React.useEffect(() => {
    if (!latestGame) {
      setLatestGame();
    }
  }, [latestGame, setLatestGame]);

  return (
    <div className="h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto max-w-3xl flex flex-wrap items-center h-full justify-around">
        <div className="w-full">
          <Code {...latestGame} />
        </div>
        <GameScore />
      </main>
    </div>
  );
};

export default Home;
