import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";

import { useGetLatestGameQuery } from "../generated/graphql";
import Code from "../components/Code";

const GameScore = dynamic(() => import("../components/GameScore"), {
  ssr: false,
});

const Home: NextPage = () => {
  const [{ data: latestGame, fetching }] = useGetLatestGameQuery();

  return (
    <div className="h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto max-w-3xl flex flex-wrap items-center h-full justify-around">
        <div className="w-full">
          <Code {...latestGame?.game[0]} />
        </div>
        <div className="text-purple-400">Guesses</div>
        <GameScore />
      </main>
    </div>
  );
};

export default Home;
